/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package empleados;

import javax.swing.JOptionPane;

public class MainForm extends javax.swing.JFrame {
    Lista lista;
    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
        lista = new Lista();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBotonLeer = new javax.swing.JButton();
        jTFTamano = new javax.swing.JTextField();
        jBotonMostrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTA = new javax.swing.JTextArea();
        jBotonBuscar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jBotonLeer.setText("Leer");
        jBotonLeer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotonLeerActionPerformed(evt);
            }
        });

        jBotonMostrar.setText("Mostrar Lista");
        jBotonMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotonMostrarActionPerformed(evt);
            }
        });

        jTA.setColumns(20);
        jTA.setRows(5);
        jScrollPane1.setViewportView(jTA);

        jBotonBuscar.setText("Buscar Empleado");
        jBotonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotonBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTFTamano, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(jBotonLeer))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(jBotonMostrar)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBotonBuscar)))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBotonLeer)
                    .addComponent(jTFTamano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBotonBuscar))
                .addGap(18, 18, 18)
                .addComponent(jBotonMostrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private Empleado cargarEmpleado(){
        int codigo = Integer.parseInt(JOptionPane.showInputDialog("Codigo:"));
        String nombre = JOptionPane.showInputDialog("Nombre:");
        String apellidoPaterno = JOptionPane.showInputDialog("Ap. Paterno:");
        String apellidoMaterno = JOptionPane.showInputDialog("Ap. Materno:");
        int sueldo = Integer.parseInt(JOptionPane.showInputDialog("Sueldo"));
        return new Empleado(codigo, nombre, apellidoPaterno, apellidoMaterno, sueldo);
    }
    
    private void jBotonLeerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotonLeerActionPerformed
        int n=Integer.parseInt(jTFTamano.getText());
        for(int i=0;i<n;i++)
        {
            lista.insertarUltimo(cargarEmpleado());
        }
    }//GEN-LAST:event_jBotonLeerActionPerformed

    private void jBotonMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotonMostrarActionPerformed
        Nodo nodo = lista.Primero();
        jTA.setText("");
        while(nodo != null){
            MostrarEmpleado(nodo.getElem());
            nodo = nodo.getProx();
        }
    }//GEN-LAST:event_jBotonMostrarActionPerformed

    private void jBotonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotonBuscarActionPerformed
        int codigo = Integer.parseInt(JOptionPane.showInputDialog("Ingrese codigo a buscar:"));
        Empleado encontrado = lista.buscarCodigo(codigo);
        if(encontrado == null){
            JOptionPane.showMessageDialog(this, "No encontrado");
        }
        else{
            jTA.setText("");
            MostrarEmpleado(encontrado);
        }
    }//GEN-LAST:event_jBotonBuscarActionPerformed

    private void MostrarEmpleado(Empleado elem) {
        jTA.append("Codigo: " + elem.getCodigo() + "\n");
        jTA.append("Nombre: " + elem.getNombre() + "\n");
        jTA.append("Paterno: " + elem.getApellidoPaterno() + "\n");
        jTA.append("Materno: " + elem.getApellidoMaterno() + "\n");
        jTA.append("Sueldo: " + elem.getSueldo() + "\n"  + "\n"  + "\n");
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBotonBuscar;
    private javax.swing.JButton jBotonLeer;
    private javax.swing.JButton jBotonMostrar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTA;
    private javax.swing.JTextField jTFTamano;
    // End of variables declaration//GEN-END:variables

}
