
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author cesar
 */
public class Form extends javax.swing.JFrame {

    /**
     * Creates new form Form
     */
    Arbol arbol;
    public Form() {
        arbol = new Arbol();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtElemento = new javax.swing.JTextField();
        jBPreorden = new javax.swing.JButton();
        jBInorden = new javax.swing.JButton();
        jBPosOrden = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTA = new javax.swing.JTextArea();
        jBInsertar = new javax.swing.JButton();
        jBSumar = new javax.swing.JButton();
        jBSumarPares = new javax.swing.JButton();
        jBContarPares = new javax.swing.JButton();
        jBAltura = new javax.swing.JButton();
        jBExiste = new javax.swing.JButton();
        jBHermanos = new javax.swing.JButton();
        jBMostrarPares = new javax.swing.JButton();
        jBCantidadHojas = new javax.swing.JButton();
        jBDevolverAbuelo = new javax.swing.JButton();
        jBRetornarHermano = new javax.swing.JButton();
        jBTieneNietos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Arboles Binarios");

        jBPreorden.setText("Preorden");
        jBPreorden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPreordenActionPerformed(evt);
            }
        });

        jBInorden.setText("InOrden");
        jBInorden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBInordenActionPerformed(evt);
            }
        });

        jBPosOrden.setText("PosOrden");
        jBPosOrden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPosOrdenActionPerformed(evt);
            }
        });

        jTA.setColumns(20);
        jTA.setRows(5);
        jScrollPane1.setViewportView(jTA);

        jBInsertar.setText("Insertar");
        jBInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBInsertarActionPerformed(evt);
            }
        });

        jBSumar.setText("Suma");
        jBSumar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSumarActionPerformed(evt);
            }
        });

        jBSumarPares.setText("Sumar Pares");
        jBSumarPares.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSumarParesActionPerformed(evt);
            }
        });

        jBContarPares.setText("Contar Pares");
        jBContarPares.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBContarParesActionPerformed(evt);
            }
        });

        jBAltura.setText("Altura");
        jBAltura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAlturaActionPerformed(evt);
            }
        });

        jBExiste.setText("Existe");
        jBExiste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBExisteActionPerformed(evt);
            }
        });

        jBHermanos.setText("Hermanos");
        jBHermanos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBHermanosActionPerformed(evt);
            }
        });

        jBMostrarPares.setText("Mostrar Pares");
        jBMostrarPares.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBMostrarParesActionPerformed(evt);
            }
        });

        jBCantidadHojas.setText("Cantidad Hojas");
        jBCantidadHojas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCantidadHojasActionPerformed(evt);
            }
        });

        jBDevolverAbuelo.setText("Abuelo");
        jBDevolverAbuelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBDevolverAbueloActionPerformed(evt);
            }
        });

        jBRetornarHermano.setText("Retornar Hermano");
        jBRetornarHermano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBRetornarHermanoActionPerformed(evt);
            }
        });

        jBTieneNietos.setText("Tiene Nietos");
        jBTieneNietos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTieneNietosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtElemento, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(jBInsertar))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jBPreorden)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jBSumar)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(53, 53, 53)
                                        .addComponent(jBInorden)
                                        .addGap(59, 59, 59)
                                        .addComponent(jBPosOrden))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(37, 37, 37)
                                        .addComponent(jBSumarPares)
                                        .addGap(36, 36, 36)
                                        .addComponent(jBContarPares)))
                                .addGap(25, 25, 25)
                                .addComponent(jBAltura))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBExiste)
                            .addComponent(jBDevolverAbuelo))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBHermanos)
                                .addGap(64, 64, 64)
                                .addComponent(jBMostrarPares)
                                .addGap(35, 35, 35)
                                .addComponent(jBCantidadHojas))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBRetornarHermano)
                                .addGap(44, 44, 44)
                                .addComponent(jBTieneNietos)))))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtElemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBInsertar))
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBPreorden)
                    .addComponent(jBInorden)
                    .addComponent(jBPosOrden)
                    .addComponent(jBAltura))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBSumar)
                    .addComponent(jBSumarPares)
                    .addComponent(jBContarPares))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBExiste)
                    .addComponent(jBHermanos)
                    .addComponent(jBMostrarPares)
                    .addComponent(jBCantidadHojas))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBDevolverAbuelo)
                    .addComponent(jBRetornarHermano)
                    .addComponent(jBTieneNietos))
                .addContainerGap(64, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBInsertarActionPerformed
        // TODO add your handling code here:
        int x = Integer.parseInt(txtElemento.getText());
        arbol.insertar(x);
        txtElemento.setText("");
    }//GEN-LAST:event_jBInsertarActionPerformed

    private void jBPreordenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPreordenActionPerformed
        arbol.preOrden(jTA);
    }//GEN-LAST:event_jBPreordenActionPerformed

    private void jBInordenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBInordenActionPerformed
        arbol.InOrden(jTA);
    }//GEN-LAST:event_jBInordenActionPerformed

    private void jBPosOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPosOrdenActionPerformed
        arbol.PostOrden(jTA);
    }//GEN-LAST:event_jBPosOrdenActionPerformed

    private void jBSumarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSumarActionPerformed
        JOptionPane.showMessageDialog(rootPane, arbol.suma());
    }//GEN-LAST:event_jBSumarActionPerformed

    private void jBSumarParesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSumarParesActionPerformed
        JOptionPane.showMessageDialog(rootPane, arbol.sumaDePares());
    }//GEN-LAST:event_jBSumarParesActionPerformed

    private void jBContarParesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBContarParesActionPerformed
        JOptionPane.showMessageDialog(rootPane, arbol.contarPares2());
    }//GEN-LAST:event_jBContarParesActionPerformed

    private void jBAlturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAlturaActionPerformed
        JOptionPane.showMessageDialog(rootPane, arbol.altura());
    }//GEN-LAST:event_jBAlturaActionPerformed

    private void jBExisteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBExisteActionPerformed
        int num;
        num = Integer.parseInt(JOptionPane.showInputDialog("Ingrese numero a buscar"));
        if(arbol.existe(num))
            JOptionPane.showMessageDialog(rootPane, "Existe");
        else
            JOptionPane.showMessageDialog(rootPane, "No existe");
    }//GEN-LAST:event_jBExisteActionPerformed

    private void jBHermanosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBHermanosActionPerformed
        int x;
        x = Integer.parseInt(JOptionPane.showInputDialog("Ingrese primer numero"));
        int y;
        y = Integer.parseInt(JOptionPane.showInputDialog("Ingrese segundo numero"));
        if(arbol.brother(x, y))
            JOptionPane.showMessageDialog(rootPane, "Son hermanos");
        else
            JOptionPane.showMessageDialog(rootPane, "No son hermanos");
    }//GEN-LAST:event_jBHermanosActionPerformed

    private void jBMostrarParesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBMostrarParesActionPerformed
        jTA.setText("");
        arbol.mostrarPares(jTA);
    }//GEN-LAST:event_jBMostrarParesActionPerformed

    private void jBCantidadHojasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCantidadHojasActionPerformed
        JOptionPane.showMessageDialog(rootPane, "Hay " + arbol.cantHojas() + " hojas en el arbol");
    }//GEN-LAST:event_jBCantidadHojasActionPerformed

    private void jBDevolverAbueloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBDevolverAbueloActionPerformed
        int abuelo = arbol.retornaAbuelo(Integer.parseInt(JOptionPane.showInputDialog("Ingrese hijo para pillar abuelo:")));
        if( abuelo != 0)
            JOptionPane.showMessageDialog(rootPane, "Su abuelo es " + abuelo);
    }//GEN-LAST:event_jBDevolverAbueloActionPerformed

    private void jBRetornarHermanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBRetornarHermanoActionPerformed
        int x = Integer.parseInt(JOptionPane.showInputDialog("Ingrese hijo para pillar hermano:"));
        JOptionPane.showMessageDialog(rootPane, arbol.retornarHermano(x));
    }//GEN-LAST:event_jBRetornarHermanoActionPerformed

    private void jBTieneNietosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTieneNietosActionPerformed
        int x = Integer.parseInt(JOptionPane.showInputDialog("Ingrese hijo para pillar si tiene nietos o no:"));
        if(arbol.existe(x))
            JOptionPane.showMessageDialog(rootPane, arbol.tieneNietos(x));
        else
            JOptionPane.showMessageDialog(rootPane, "No existe un nodo con ese valor");
    }//GEN-LAST:event_jBTieneNietosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAltura;
    private javax.swing.JButton jBCantidadHojas;
    private javax.swing.JButton jBContarPares;
    private javax.swing.JButton jBDevolverAbuelo;
    private javax.swing.JButton jBExiste;
    private javax.swing.JButton jBHermanos;
    private javax.swing.JButton jBInorden;
    private javax.swing.JButton jBInsertar;
    private javax.swing.JButton jBMostrarPares;
    private javax.swing.JButton jBPosOrden;
    private javax.swing.JButton jBPreorden;
    private javax.swing.JButton jBRetornarHermano;
    private javax.swing.JButton jBSumar;
    private javax.swing.JButton jBSumarPares;
    private javax.swing.JButton jBTieneNietos;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTA;
    private javax.swing.JTextField txtElemento;
    // End of variables declaration//GEN-END:variables
}
